#!/bin/bash

# Get location of nbws
# from Dave Dopson at http://stackoverflow.com/a/246128/986793
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"



export TMP=$(mktemp -u)
mkfifo $TMP.fifo
export BROWSER="echo >$TMP.fifo"

cd "$DIR"
python -m mod_pywebsocket.standalone -p 8888 -d . &
echo $! >$TMP.pid 
cd - 


echo please visit http://$(hostname):8888
sleep 3


newsbeuter

echo $TMP $TMP.pid $TMP.fifo "'$BROWSER'"
kill $(<$TMP.pid)
rm $TMP.pid $TMP.fifo
